@baseUrl = http://ec2-18-197-98-20.eu-central-1.compute.amazonaws.com:3000
@cookie = auth="86a48dc5-04d4-4ddb-b97b-31fde0321d57"

###
GET {{baseUrl}}/api/v1/current/user
Content-Type: application/json
Cookie: {{cookie}}

{
  "role": "admin",
  "username": "decker"
}
